### ISSUE TITLE
[11.0][sale_variant_configurator] Key error when trying to choose a product template

### ISSUE THREAD

**Issue by SalahAdDin** [OCA/product-variant#117]
Hello,

I'm working with this module in order to manage all size variants in an easy way, but I'm getting a bug.

I installed this module in a pre-existing database with all my product with their respective variants, no problems; i go to the sale module and i create a new sale, i try to choose a product as a product template and i get this:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5099, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4994, in _onchange_eval
    method_res = method(self)
  File "/var/lib/odoo/addons/11.0/product-variant/sale_variant_configurator/models/sale_order.py", line 52, in _onchange_product_tmpl_id_configurator
    self.order_id.partner_id.id)[self.order_id.pricelist_id.id]
KeyError: False
```

Why?

Odoo 11.0-20181126 (Community Edition)

**Comment by pedrobaeza** [comment]
Try to reproduce the problem the problem on OCA runbot.

**Comment by pedrobaeza** [comment]
Any way, it seems there's no pricelist selected, so that can be the problem.

**Comment by SalahAdDin** [comment]
I found the problem: Before to choose a product we must to select a pricelist.

**Comment by SalahAdDin** [comment]
Also i think that for `product_variant_default_code` we also to update the documentation:
if we want to modify the `reference-mask` we must enable manual mask since options.

Should i make a pull request?
