### ISSUE TITLE
[11.0] [product_variant] Error when starting inventory adjustment

### ISSUE THREAD

**Issue by sacostaylara** [OCA/product-variant#132]
module: product_variant_configurator
version: 11.0

**Steps to reproduce**
Create an inventory adjustment and click on 'Start Inventory'

**Current behavior**
Odoo Server Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/addons/stock/models/stock_inventory.py", line 197, in action_start
    vals.update({'line_ids': [(0, 0, line_values) for line_values in inventory._get_inventory_lines_values()]})
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/addons/stock/models/stock_inventory.py", line 260, in _get_inventory_lines_values
    GROUP BY product_id, location_id, lot_id, package_id, partner_id """ % domain, args)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odoo-11.0+e.20181225-py3.5.egg/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column reference "product_id" is ambiguous
LINE 4:             ON product_product.id = product_id

**Expected behavior**
Inventory adjustment started

**Comment by pedrobaeza** [comment]
I'm aware of this, but it's not a direct problem of the module, but the SQL query used on inventory that uses a not fully qualified field name `product_id` in it. This should be fixed at Odoo level. You can propose a PR/issue to Odoo for fixing it.

**Comment by sacostaylara** [comment]
Ok, thanks for your answer Pedro. Will propose a pull request when I have time. Guess we can close this issue.

**Comment by pedrobaeza** [comment]
Note that it's being discussed in https://github.com/odoo/odoo/pull/30307
