### ISSUE TITLE
[13.0} product_variant_configurator error when select product template in add product Variant

### ISSUE THREAD

**Issue by anxoa77** [OCA/product-variant#194]
I just installed the module and I don't know if it's me doing something wrong, or if it's the module.

I have created a product template without creating the variants. When I go to the product variant, it lets me select the product template, but when I select it, I get the following error

I hope you can help me
Greetings

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: <NewId 0x7f4f623ee9b0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/fields.py", line 1002, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo13/odoo/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('product.product(<NewId 0x7f4f623ee9b0>,).website_url', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
KeyError: <NewId origin=5570>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/fields.py", line 1002, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo13/odoo/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('product.template(<NewId origin=5570>,).website_url', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/models.py", line 6124, in onchange
    for name in nametree
  File "/opt/odoo13/odoo/odoo/models.py", line 6125, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/opt/odoo13/odoo/odoo/models.py", line 5992, in has_changed
    return self[name] != record[name]
  File "/opt/odoo13/odoo/odoo/models.py", line 5640, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo13/odoo/odoo/fields.py", line 1026, in __get__
    self.compute_value(recs)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1111, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo13/odoo/odoo/models.py", line 3939, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo13/odoo/addons/website_sale/models/product.py", line 418, in _compute_product_website_url
    product.website_url = "%s#attr=%s" % (product.product_tmpl_id.website_url, attributes)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1026, in __get__
    self.compute_value(recs)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1111, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo13/odoo/odoo/models.py", line 3939, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo13/odoo/addons/website_sale/models/product.py", line 379, in _compute_website_url
    product.website_url = "/shop/product/%s" % slug(product)
  File "/opt/odoo13/odoo/addons/http_routing/models/ir_http.py", line 91, in slug
    raise ValueError("Cannot slug non-existent record %s" % value)
ValueError: Cannot slug non-existent record product.template(<NewId origin=5570>,)

**Comment by pedrobaeza** [comment]
Duplicated of #192 

The module is incompatible with `website_sale`.

**Comment by anxoa77** [comment]
Thank you very much for the answer, sorry I didn't see #192
