### ISSUE TITLE
[14.0][BUG] product_variant_inactive - broken after uninstall

### ISSUE THREAD

**Issue by ilyasProgrammer** [OCA/product-variant#310]
Module: product_variant_inactive 

Version: 14.0

How to reproduce:

- Create product template
- Add attributes and values. Save.
- Unistall product_variant_inactive .
- Go back to product. Click Variants.
- You will see error:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field product.product.combination_deleted in leaf ('combination_deleted', '!=', True)
```

**Comment by ilyasProgrammer** [comment]
product.product_variant_action ir.actions.act_window still have  <field name="domain">[('combination_deleted', '!=', True)]</field>   after uninstall
