### ISSUE TITLE
Cannot add variant price in the vendor pricelists 

### ISSUE THREAD

**Issue by thygesen** [OCA/product-variant#71]
Trying to add vendors variant price

Selects a vendor
Selects product
Selects variant ... BUM!

Uncaught Error: KeyError: 'id'

http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1585
Traceback:
Error: KeyError: 'id'
    at F.__getitem__ (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1585:161)
    at F.__getattr__ (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1586:69)
    at F.__getattribute__ (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1385:38)
    at Object.py.PY_getAttr (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1349:176)
    at Object.py.evaluate (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1452:11)
    at Object.py.evaluate (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1447:111)
    at Object.py.evaluate (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1449:99)
    at Object.py.eval (http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1454:284)
    at http://localhost:8069/web/content/4480-7039b89/web.assets_backend.js:1596:136
    at Function._.each._.forEach (http://localhost:8069/web/content/4172-629d75f/web.assets_common.js:12:558)

**Comment by coreuter** [comment]
I had this issue too and resolved it by changing the domain definition in 'product_supplierinfo_view.xml' from `domain="[('product_tmpl_id', '=', parent.id)]"` to `domain="[('product_tmpl_id', '=', product_tmpl_id)]"`

In addition I added following snippet to 'product_supplierinfo.py' to automatically clear the product variant field as soon as the product template is changed:
```
@api.onchange('product_tmpl_id')
    def onchange_product_template(self):
        self.product_id = False
```

So far this is working without any issues with the latest Odoo 10 (commit 68934c6)

**Comment by Nucleardragon88** [comment]
same problem with Odoo 10

**Comment by pedrobaeza** [comment]
Which module?

**Comment by pedrobaeza** [comment]
No answer, so I close.
